version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/project
    networks:
      - serializer
    working_dir: /var/www/project
    environment:
      - SSH_AUTH_SOCK
      - COMPOSER_ALLOW_SUPERUSER=1

networks:
  serializer:
    external:
        name: serializer
