App\Entity\AbstractDummyA:
    attributes:
        a:
            groups: ['test']
    discriminator_map:
        type_property: 'type'
        mapping:
            b: 'App\Entity\DummyB'

App\Entity\DummyB:
    attributes:
        b:
            groups: ['test']