App\Entity\AbstractDummyA:
    attributes:
        a:
            groups: ['test']
    discriminator_map:
        type_property: 'type'
        mapping:
            b: 'App\Entity\DummyB'
            c: 'App\Entity\DummyC'
            d: 'App\Entity\DummyD'

App\Entity\DummyB:
    attributes:
        b:
            groups: ['test']

App\Entity\DummyC:
    attributes:
        c:
            groups: ['test']

App\Entity\DummyD:
    attributes:
        dummyC:
            groups: ['test']
        d:
            groups: ['test']